name: Build

on:
  push:
    branches:
      - "main"
      - "release-*"
      # TODO - remove this
      - "gha-migration"
    tags:
      - "*"
  pull_request:
    branches:
      - "*"

# Declare default permissions as read only
permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    name: Prepare Kafka Binaries
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/build/prepare-kafka
        with:
          runnerArch: "amd64"

  build-containers:
    name: Build Containers
    needs:
      - prepare
    strategy:
      matrix:
        architecture:
          - amd64
          - arm64
          - s390x
          - ppc64le
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/build/build-containers
        with:
          architecture: ${{ matrix.architecture }}
          runnerArch: "amd64"

  push-containers:
    name: Push Containers
    needs:
      - build-containers
    if: ${{ github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/build/push-containers
        with:
          architectures: "amd64 arm64 s390x ppc64le"
          runnerArch: "amd64"
          quayUser: ${{ secrets.QUAY_USER }}
          quayPass: ${{ secrets.QUAY_PASS }}